import { defineTool } from '@deepseek-ai/dsh-tools'
import type { GithubEngine } from './engine.ts'
type ContentBlock = { type: 'text'; text: string }
function text(value: string): ContentBlock[] { return [{ type: 'text', text: value }] }
function render(value: unknown): string { return JSON.stringify(value, null, 2) }
function jsonValue(value: unknown): any { return JSON.parse(JSON.stringify(value)) }
const schema = { type: 'json' } as const
export function githubAuthListTool(engine: GithubEngine) { return defineTool({ name: 'github_auth_list', description: 'List configured GitHub accounts without revealing tokens. Use before GitHub repository or Git operations when the account alias is unknown.', parameters: {}, output: { schema, render: (_args, value) => text(render(value)) }, async execute() { return jsonValue({ accounts: engine.listAccounts() }) } }) }
export function githubAuthTestTool(engine: GithubEngine) { return defineTool({ name: 'github_auth_test', description: 'Test a configured GitHub account and return the authenticated username. Never returns the token.', parameters: { account: { type: 'string', description: 'Configured account alias. Omit when the default account is configured.' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.testAccount(args.account)) } }) }
export function githubRepoListTool(engine: GithubEngine) { return defineTool({ name: 'github_repo_list', description: 'List repositories visible to a configured GitHub account, optionally filtered by name. Returns repository metadata and clone URLs.', parameters: { account: { type: 'string', description: 'Configured account alias.' }, query: { type: 'string', description: 'Optional name or description filter.' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue({ repos: await engine.listRepos(args.account, args.query) }) } }) }
export function githubCloneTool(engine: GithubEngine) { return defineTool({ name: 'github_clone', description: 'Clone a GitHub repository into an absolute local destination using a configured GitHub account. The token is sent through an ephemeral Git HTTP header and is never put in the URL.', parameters: { remoteUrl: { type: 'string', required: true, description: 'HTTPS clone URL or owner/repository.' }, destination: { type: 'string', required: true, description: 'Absolute local destination directory.' }, account: { type: 'string', description: 'Configured account alias.' }, branch: { type: 'string', description: 'Optional branch.' }, timeoutMs: { type: 'integer', description: 'Timeout in milliseconds.' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'clone', ...args })) } }) }
export function githubPullTool(engine: GithubEngine) { return defineTool({ name: 'github_pull', description: 'Fast-forward pull one local Git repository from GitHub. Requires an absolute repository path and a configured account.', parameters: { repoPath: { type: 'string', required: true, description: 'Absolute local Git repository path.' }, account: { type: 'string', description: 'Configured account alias.' }, remote: { type: 'string', description: 'Remote name, default origin.' }, branch: { type: 'string', description: 'Optional branch.' }, timeoutMs: { type: 'integer', description: 'Timeout in milliseconds.' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'pull', ...args })) } }) }
export function githubPushTool(engine: GithubEngine) { return defineTool({ name: 'github_push', description: 'Push one local Git repository to GitHub. Push is disabled by default and must be enabled in the GitHub panel; force push additionally requires the force-push switch.', parameters: { repoPath: { type: 'string', required: true, description: 'Absolute local Git repository path.' }, account: { type: 'string', description: 'Configured account alias.' }, remote: { type: 'string', description: 'Remote name, default origin.' }, branch: { type: 'string', description: 'Optional branch.' }, force: { type: 'boolean', description: 'Use force-with-lease; requires the force-push switch.' }, timeoutMs: { type: 'integer', description: 'Timeout in milliseconds.' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'push', ...args })) } }) }
export function githubStatusTool(engine: GithubEngine) { return defineTool({ name: 'github_status', description: 'Read local Git status for an absolute repository path, including branch and changed files.', parameters: { repoPath: { type: 'string', required: true, description: 'Absolute local Git repository path.' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'status', ...args })) } }) }
export function githubCommitTool(engine: GithubEngine) { return defineTool({ name: 'github_commit', description: 'Create a local Git commit. This does not push; call github_push separately after reviewing the result.', parameters: { repoPath: { type: 'string', required: true, description: 'Absolute local Git repository path.' }, message: { type: 'string', required: true, description: 'Commit message.' }, all: { type: 'boolean', description: 'Stage all tracked and untracked changes before committing.' }, account: { type: 'string', description: 'Configured account alias.' }, timeoutMs: { type: 'integer', description: 'Timeout in milliseconds.' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'commit', ...args })) } }) }
