import type { PanelController } from './controller.ts'
const ICON = '<svg viewBox="0 0 16 16" width="14" height="14" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="8" cy="8" r="5.6"/><path d="M5.9 6.7c-.25-.45-.25-.95 0-1.3M10.1 6.7c.25-.45.25-.95 0-1.3"/><path d="M5.6 10.6c.55.7 2.2 1.05 3.2 0M6.4 3.5l-1.1-1.2M9.6 3.5l1.1-1.2M8 13.6V11.2M5.7 11.8L8 11.2M10.3 11.8L8 11.2"/></svg>'
function root(): HTMLElement | undefined { const column = document.querySelector<HTMLElement>('[data-pane="sidebar"], [class*="sidebarCol"]'); if (!column) return undefined; return column.querySelector<HTMLElement>('[class*="logoRow"]')?.parentElement ?? column.firstElementChild as HTMLElement | undefined }
export function mountSidebar(controller: PanelController): () => void {
  const selector = '[data-dsh-github-entry]'; if (document.querySelector(selector)) return () => {}
  const entry = document.createElement('button'); entry.type = 'button'; entry.setAttribute('data-dsh-github-entry', ''); entry.setAttribute('data-dsh-plugin', 'github'); entry.setAttribute('aria-label', 'GitHub'); entry.title = 'GitHub'; entry.className = 'NS3bAW_entry'; entry.innerHTML = '<span class="NS3bAW_entryIcon">' + ICON + '</span><span class="NS3bAW_entryLabel">GitHub</span>'; entry.addEventListener('click', () => controller.toggle())
  let placed = false; const place = (): void => { const container = root(); if (!container) return; const anchor = container.querySelector('button[class*="newSession"]') ?? container.firstElementChild; if (!placed || !entry.isConnected) { container.insertBefore(entry, anchor?.nextSibling ?? null); placed = true } if (controller.getSnapshot().open) entry.dataset.active = 'true'; else delete entry.dataset.active }
  const observer = new MutationObserver(place); observer.observe(document.body, { childList: true, subtree: true }); const unsubscribe = controller.subscribe(place); place()
  return () => { observer.disconnect(); unsubscribe(); entry.remove() }
}
